### ISSUE TITLE
Add in "next block adjustment time"

### ISSUE THREAD

**Issue by mooleshacat** [EasyX-Community/easyNOMP#144]
**Try to add in "next block adjustment time" from this pool here:**
http://mnx.szzpool.com/stats/minexcoin

**If this is your pool** please fork the project and make a pull request to add this feature in and credit your GitHub account!

**Comment by SongZhizhai** [comment]
<td style="text-align:center;">{{=961-(it.stats.pools[pool].poolStats.networkBlocks%960)}} blocks（约{{=3*(961-(it.stats.pools[pool].poolStats.networkBlocks%960))/60}} hours）</td>

the number of "3" is that the network will found a block in 3min.
the number of "960" is that the network will change the difficulty every 960 blocks.

**Comment by mooleshacat** [comment]
Done and done, thank you :D

I will credit your GitHub username and link to the profile :)

**Comment by mooleshacat** [comment]
**Reopened** times are wrong :P

**@SongZhizhai says:**

> you have a problem
> ![image](https://cdn.discordapp.com/attachments/499486944452018176/509642758424625152/unknown.png)
> is not suitable for all coins
> So you can't add it like this
> such minexcoin
> in /src/chainparams.cpp
> for example minexcoin:   in its code:    /src/chainparams.cpp
> ![image](https://cdn.discordapp.com/attachments/499486944452018176/509644579616718848/unknown.png)
> 960=2x24x60x60/3/60(edited)
> 3 is three minutes
> every coin is not same
> so you have to add a parameter in /coins/*.conf to set the "960" and "3"

**Comment by mooleshacat** [comment]
moved to https://github.com/EasyX-Community/EasyNOMP/issues/24

**Comment by mooleshacat** [comment]
This has been added to EasyNOMP
