### ISSUE TITLE
Add in "difficulty change in _ hours"

### ISSUE THREAD

**Issue by leshacat** [EasyX-Community/EasyNOMP#24]
@leshacat commented on 1 Nov 2018
Try to add in "next block adjustment time" from this pool here:
http://mnx.szzpool.com/stats/minexcoin

If this is your pool please fork the project and make a pull request to add this feature in and credit your GitHub account!

@leshacat leshacat added Enhancement Help Wanted Feature Request Low Priority v1.1.4 finalization v1.1.5 GUI / Website Bug and removed Feature Request labels on 1 Nov 2018
@SongZhizhai
 
@SongZhizhai commented on 6 Nov 2018 • 
{{=961-(it.stats.pools[pool].poolStats.networkBlocks%960)}} blocks（约{{=3*(961-(it.stats.pools[pool].poolStats.networkBlocks%960))/60}} hours）
the number of "3" is that the network will found a block in 3min.
the number of "960" is that the network will change the difficulty every 960 blocks.

@leshacat
 MemberAuthor
leshacat commented on 6 Nov 2018
Done and done, thank you :D

I will credit your GitHub username and link to the profile :)

@leshacat leshacat closed this on 6 Nov 2018
@leshacat leshacat added Fixed/Completed! and removed GUI / Website Bug Help Wanted labels on 6 Nov 2018
@leshacat leshacat reopened this on 7 Nov 2018
@leshacat
 MemberAuthor
leshacat commented on 7 Nov 2018 • 
Reopened times are wrong :P

@SongZhizhai says:

you have a problem
 ![image](https://cdn.discordapp.com/attachments/499486944452018176/509642758424625152/unknown.png)
is not suitable for all coins
So you can't add it like this
such minexcoin
in /src/chainparams.cpp
for example minexcoin: in its code: /src/chainparams.cpp
![image](https://cdn.discordapp.com/attachments/499486944452018176/509644579616718848/unknown.png)
960=2x24x60x60/3/60(edited)
3 is three minutes
every coin is not same
so you have to add a parameter in /coins/*.conf to set the "960" and "3"

@leshacat leshacat added Needs Investigating Nearly Fixed/Completed! and removed Fixed/Completed! labels on 7 Nov 2018

**Comment by mooleshacat** [comment]
Completed
