### ISSUE TITLE
Android App - Contact 1

### ISSUE THREAD

**Issue by leshacat** [EasyX-Community/EasyNOMP#41]
Not 100% sure what you'd actually do with a nomp app, but I potentially have enough android experience to make a start!

_Originally posted by @sakza in https://github.com/EasyX-Community/EasyNOMP-dev-OLD/issues/155#issuecomment-462017693_

**Comment by mooleshacat** [comment]
Hey @sakza are you still interested?

You would need to know how to parse JSON and display it on screen. Mostly string manipulation and displaying the data.

If you're still interested, join our discord server or get on my live support on the pool website http://easyxpool.tk/

**Comment by sazka** [comment]
wrong user you want @sakza

**Comment by mooleshacat** [comment]
Haha sorry, @sazka ....

@sakza are you there?

**Comment by mooleshacat** [comment]
I guess not, closing issue.
