### ISSUE TITLE
File missing: libs/functions.js

### ISSUE THREAD

**Issue by arch-linux** [EasyX-Community/EasyNOMP#57]
Hello!

I have installed easyNOMP several times following the dependency installs and completed all successfully however I always end up with the following error.

Im running the latest ubuntu server with a full distribution upgrade.

`EasyNOMP Watching Logs...

Script name : /home/pool/EasyNOMP/EasyNOMP/pool-logs-watch.sh
Current working dir : /home/pool/EasyNOMP/EasyNOMP
Script location path (dir) : /home/pool/EasyNOMP/EasyNOMP

[TAILING] Tailing last 15 lines for [pool] process (change the value with --lines option)
/root/.pm2/logs/pool-out.log last 15 lines:
/root/.pm2/logs/pool-error.log last 15 lines:
0|pool     | module.js:487
0|pool     |     throw err;
0|pool     |     ^
0|pool     |
0|pool     | Error: Cannot find module './functions.js'
0|pool     |     at Function.Module._resolveFilename (module.js:485:15)
0|pool     |     at Function.Module._load (module.js:437:25)
0|pool     |     at Module.require (module.js:513:17)
0|pool     |     at require (internal/module.js:11:18)
0|pool     |     at Object.<anonymous> (/home/pool/EasyNOMP/EasyNOMP/libs/poolWorker.js:5:19)
0|pool     |     at Module._compile (module.js:569:30)
0|pool     |     at Object.Module._extensions..js (module.js:580:10)
0|pool     |     at Module.load (module.js:503:32)
0|pool     |     at tryModuleLoad (module.js:466:12)
0|pool     |     at Function.Module._load (module.js:458:3)
` 

Like I said before, I have performed several clean installs always resulting in the same error.

**Comment by mooleshacat** [comment]
Try once more, it seems I forgot to add the file **libs/functions.js** to the commit.

```
git pull
npm update
```
should be all you need to do from source directory.

Sorry about that :wave:

**Comment by arch-linux** [comment]
Sweet! Closing the issue ticker.

Thanks!
